In [1]:
import pandas as pd

In [4]:
# spring = pd.read_csv("./data/silver/model_datasets/dataset_train_spring.csv")
summer_train = pd.read_csv("./data/gold/dataset_full_summer_clean.csv")

In [ ]:
summer_train = summer_train.dropna(subset=["label"])

,elevation,slope,aspect,d_roads,d_rivers,d_buildings,landuse_class,tas,tasmax,tasmin,rainfall,sfcWind,hurs,diurnal_range,ndvi,d_fires,label,_x,_y
0,34.848118,1.377466,178.970700,0.180000,0.000000,0.966074,0.0,17.343870,23.481167,11.218638,42.202774,3.597540,71.489660,12.262529,0.679766,1.741034,NaN,583904.6,246574.2
1,34.143665,0.874824,101.301970,0.150000,0.000000,0.948683,0.0,17.346113,23.483143,11.220788,42.231080,3.595676,71.490090,12.262356,0.675463,1.742326,NaN,583934.6,246574.2
2,34.979618,0.762946,45.734650,0.090000,0.000000,0.915860,0.0,17.350595,23.487097,11.225087,42.287697,3.591949,71.490944,12.262009,0.666672,1.746454,NaN,583994.6,246574.2
3,35.480114,1.821862,177.423460,0.180000,0.000000,0.960469,0.0,17.346983,23.485540,11.220055,42.102406,3.593614,71.488930,12.265487,0.685102,1.710263,NaN,583874.6,246544.2
4,34.093437,1.620773,150.028930,0.182483,0.030000,0.942019,0.0,17.349104,23.487370,11.222132,42.133076,3.591896,71.489340,12.265238,0.681774,1.711052,NaN,583904.6,246544.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3851110,1.518249,0.549430,337.976900,0.094868,0.600750,0.123693,0.0,18.211172,23.316265,13.160004,24.598675,3.962569,72.836044,10.156262,0.246605,0.600750,NaN,578744.6,181954.2
3851111,1.112317,2.978706,123.436950,0.090000,0.611882,0.060000,0.0,18.208560,23.318167,13.152250,24.571262,3.956777,72.817710,10.165917,0.246605,0.655210,NaN,578594.6,181924.2
3851112,0.827998,1.999139,98.737430,0.090000,0.618466,0.060000,5.0,18.209084,23.317787,13.153801,24.576744,3.957936,72.821380,10.163986,0.246605,0.647611,NaN,578624.6,181924.2
3851113,0.794172,1.685524,92.195920,0.090000,0.626418,0.067082,5.0,18.209604,23.317408,13.155352,24.582226,3.959094,72.825040,10.162055,0.246605,0.641327,NaN,578654.6,181924.2
3851114,0.760347,1.504315,92.460724,0.094868,0.630000,0.084853,0.0,18.210127,23.317026,13.156902,24.587710,3.960252,72.828710,10.160124,0.246605,0.636396,NaN,578684.6,181924.2

In [3]:
def show_summary(df):
    temp_df = df.copy()
    # temp_df = temp_df.drop(columns=["label"], inplace = False).copy()
    summary_df = temp_df.describe().T
    summary_df["nan (%)"] = 100 * temp_df.isna().sum() / len(temp_df)
    return summary_df

In [4]:
show_summary(spring)

,count,mean,std,min,25%,50%,75%,max,nan (%)
elevation,3851135.0,52.236627,32.225412,-11.406961,24.754438,53.000000,77.078355,155.993200,0.000000
slope,3851135.0,2.096079,1.485652,0.000000,1.069072,1.768091,2.730465,22.356083,0.000000
aspect,3851135.0,176.065386,100.933582,0.000000,91.410355,175.375240,263.065060,359.999940,0.000000
d_roads,3851135.0,0.178238,0.184750,0.000000,0.042426,0.123693,0.256320,2.151023,0.000000
d_rivers,3851135.0,0.681790,0.511006,0.000000,0.268328,0.589407,0.999050,3.789512,0.000000
d_buildings,3851135.0,0.324048,0.267921,0.000000,0.123693,0.270000,0.458912,2.151023,0.000000
landuse_class,3851135.0,1.404354,1.033211,0.000000,0.000000,2.000000,2.000000,9.000000,0.000000
tas,3812267.0,9.699264,0.267357,8.949219,9.526236,9.703602,9.877433,10.831801,1.009261
tasmax,3812267.0,14.100700,0.297309,12.785580,13.919038,14.122565,14.285435,15.201936,1.009261
tasmin,3812267.0,4.830519,0.423807,3.818218,4.508735,4.805495,5.125389,6.189627,1.009261
rainfall,3812267.0,35.475906,1.717162,29.560793,34.311125,35.644190,36.648903,41.676865,1.009261
sfcWind,3812267.0,4.035682,0.254410,2.991093,3.891036,4.023839,4.153127,5.252577,1.009261
hurs,3812267.0,77.684774,0.687741,74.571080,77.303314,77.714470,78.075790,80.002310,1.009261
diurnal_range,3812267.0,9.270180,0.518730,6.779411,9.006116,9.372472,9.623017,10.443995,1.009261
ndvi,3849406.0,0.633257,0.077659,-0.099214,0.606974,0.647615,0.680385,0.821864,0.044896
label,874525.0,0.348673,0.595825,0.000000,0.000000,0.000000,1.000000,3.000000,77.291759
_x,3851135.0,576563.095219,20374.747030,536954.800000,560204.800000,575564.800000,591104.800000,626684.800000,0.000000
_y,3851135.0,215655.642671,15411.022375,181924.200000,202504.200000,216724.200000,228274.200000,246574.200000,0.000000

In [5]:
show_summary(summer)

,count,mean,std,min,25%,50%,75%,max,nan (%)
elevation,3851135.0,52.236627,32.225412,-11.406961,24.754438,53.000000,77.078355,155.993200,0.000000
slope,3851135.0,2.096079,1.485652,0.000000,1.069072,1.768091,2.730465,22.356083,0.000000
aspect,3851135.0,176.065386,100.933582,0.000000,91.410355,175.375240,263.065060,359.999940,0.000000
d_roads,3851135.0,0.178238,0.184750,0.000000,0.042426,0.123693,0.256320,2.151023,0.000000
d_rivers,3851135.0,0.681790,0.511006,0.000000,0.268328,0.589407,0.999050,3.789512,0.000000
d_buildings,3851135.0,0.324048,0.267921,0.000000,0.123693,0.270000,0.458912,2.151023,0.000000
landuse_class,3851135.0,1.404354,1.033211,0.000000,0.000000,2.000000,2.000000,9.000000,0.000000
tas,3812267.0,17.043790,0.316293,16.238495,16.815197,17.035723,17.289874,18.191456,1.009261
tasmax,3812267.0,22.068213,0.289433,20.867561,21.866846,22.111254,22.287666,22.945080,1.009261
tasmin,3812267.0,12.017823,0.531229,10.896045,11.630419,11.958335,12.358988,13.822916,1.009261
rainfall,3812267.0,55.271046,4.819824,41.496080,51.686714,55.344673,58.998550,73.831900,1.009261
sfcWind,3812267.0,3.722723,0.246004,2.789979,3.591061,3.693634,3.805871,5.076184,1.009261
hurs,3812267.0,75.649677,0.652529,73.082190,75.311322,75.768234,76.120235,77.980920,1.009261
diurnal_range,3812267.0,10.050390,0.597249,7.088060,9.777110,10.162309,10.404355,11.371709,1.009261
ndvi,3849402.0,0.556311,0.078070,-0.064664,0.510854,0.549026,0.599649,0.852116,0.045000
label,1240202.0,0.378349,0.631759,0.000000,0.000000,0.000000,1.000000,3.000000,67.796455
_x,3851135.0,576563.095219,20374.747030,536954.800000,560204.800000,575564.800000,591104.800000,626684.800000,0.000000
_y,3851135.0,215655.642671,15411.022375,181924.200000,202504.200000,216724.200000,228274.200000,246574.200000,0.000000

In [6]:
show_summary(fall)

,count,mean,std,min,25%,50%,75%,max,nan (%)
elevation,3851135.0,52.236627,32.225412,-11.406961,24.754438,53.000000,77.078355,155.993200,0.000000
slope,3851135.0,2.096079,1.485652,0.000000,1.069072,1.768091,2.730465,22.356083,0.000000
aspect,3851135.0,176.065386,100.933582,0.000000,91.410355,175.375240,263.065060,359.999940,0.000000
d_roads,3851135.0,0.178238,0.184750,0.000000,0.042426,0.123693,0.256320,2.151023,0.000000
d_rivers,3851135.0,0.681790,0.511006,0.000000,0.268328,0.589407,0.999050,3.789512,0.000000
d_buildings,3851135.0,0.324048,0.267921,0.000000,0.123693,0.270000,0.458912,2.151023,0.000000
landuse_class,3851135.0,1.404354,1.033211,0.000000,0.000000,2.000000,2.000000,9.000000,0.000000
tas,3812267.0,11.621484,0.294600,10.931639,11.399697,11.584021,11.817821,12.571111,1.009261
tasmax,3812267.0,15.399766,0.249665,14.687833,15.231673,15.431907,15.592942,16.049679,1.009261
tasmin,3812267.0,7.757186,0.445034,6.987324,7.426292,7.661613,7.977471,9.564424,1.009261
rainfall,3812267.0,53.973288,2.996279,42.480446,51.872652,53.628403,55.803159,67.418205,1.009261
sfcWind,3812267.0,3.854305,0.326982,2.667260,3.664676,3.846055,4.025808,5.490137,1.009261
hurs,3812267.0,84.475593,0.451831,82.582060,84.259480,84.584595,84.779410,85.214980,1.009261
diurnal_range,3812267.0,7.642579,0.409501,5.642183,7.418205,7.687786,7.913113,8.801144,1.009261
ndvi,3849181.0,0.519600,0.097331,-0.117679,0.451377,0.513069,0.586462,0.776017,0.050738
label,872293.0,0.318477,0.566561,0.000000,0.000000,0.000000,1.000000,3.000000,77.349716
_x,3851135.0,576563.095219,20374.747030,536954.800000,560204.800000,575564.800000,591104.800000,626684.800000,0.000000
_y,3851135.0,215655.642671,15411.022375,181924.200000,202504.200000,216724.200000,228274.200000,246574.200000,0.000000