In [1]:
import pandas as pd

In [2]:
spring = pd.read_csv("./data/silver/model_datasets/dataset_clean_spring.csv")
summer = pd.read_csv("./data/silver/model_datasets/dataset_clean_summer.csv")
fall = pd.read_csv("./data/silver/model_datasets/dataset_clean_fall.csv")

In [3]:
def show_summary(df):
    temp_df = df.drop(columns=["label"], inplace = False).copy()
    summary_df = temp_df.describe().T
    summary_df["nan (%)"] = 100 * temp_df.isna().sum() / len(temp_df)
    return summary_df

In [4]:
show_summary(spring)

,count,mean,std,min,25%,50%,75%,max,nan (%)
elevation,3851135.0,52.236627,32.225412,-11.406961,24.754438,53.000000,77.078355,155.993200,0.000000
slope,3851135.0,2.096079,1.485652,0.000000,1.069072,1.768091,2.730465,22.356083,0.000000
aspect,3851135.0,176.065386,100.933582,0.000000,91.410355,175.375240,263.065060,359.999940,0.000000
d_roads,3851135.0,0.178238,0.184750,0.000000,0.042426,0.123693,0.256320,2.151023,0.000000
d_rivers,3851135.0,0.681790,0.511006,0.000000,0.268328,0.589407,0.999050,3.789512,0.000000
d_activity,3851135.0,0.036372,0.100837,0.000000,0.000000,0.000000,0.030000,1.623884,0.000000
tas,3812267.0,9.811313,0.270158,9.055663,9.633793,9.814873,9.991230,10.937005,1.009261
tasmax,3812267.0,14.235613,0.296591,12.921712,14.054627,14.257624,14.420099,15.332370,1.009261
tasmin,3812267.0,4.940136,0.421263,3.929459,4.620185,4.916285,5.231530,6.282062,1.009261
rainfall,3812267.0,36.701918,1.678954,31.146990,35.549639,36.853645,37.864456,42.792923,1.009261
sfcWind,3812267.0,4.011789,0.249151,2.986282,3.869303,4.000361,4.126778,5.207550,1.009261
hurs,3812267.0,78.440073,0.694261,75.316986,78.012545,78.482346,78.871990,80.656044,1.009261
ndvi,3849285.0,0.638732,0.078258,-0.099214,0.613960,0.654129,0.685693,0.821877,0.048038
d_fires,3851135.0,1.173821,0.923964,0.000000,0.499300,0.969330,1.604649,7.998250,0.000000

In [5]:
show_summary(summer)

,count,mean,std,min,25%,50%,75%,max,nan (%)
elevation,3851135.0,52.236627,32.225412,-11.406961,24.754438,53.000000,77.078355,155.993200,0.000000
slope,3851135.0,2.096079,1.485652,0.000000,1.069072,1.768091,2.730465,22.356083,0.000000
aspect,3851135.0,176.065386,100.933582,0.000000,91.410355,175.375240,263.065060,359.999940,0.000000
d_roads,3851135.0,0.178238,0.184750,0.000000,0.042426,0.123693,0.256320,2.151023,0.000000
d_rivers,3851135.0,0.681790,0.511006,0.000000,0.268328,0.589407,0.999050,3.789512,0.000000
d_activity,3851135.0,0.036372,0.100837,0.000000,0.000000,0.000000,0.030000,1.623884,0.000000
tas,3812267.0,16.995465,0.315768,16.194021,16.766573,16.984562,17.239683,18.152090,1.009261
tasmax,3812267.0,22.106914,0.289327,20.901880,21.907335,22.151592,22.325686,22.982124,1.009261
tasmin,3812267.0,11.928696,0.536470,10.803248,11.537601,11.865743,12.271520,13.754824,1.009261
rainfall,3812267.0,54.701473,3.988662,41.814950,51.679848,54.761310,57.669462,71.715030,1.009261
sfcWind,3812267.0,3.726346,0.242464,2.804453,3.594974,3.699291,3.810217,5.057589,1.009261
hurs,3812267.0,75.402250,0.663431,72.851450,75.060650,75.513010,75.886345,77.745930,1.009261
ndvi,3849358.0,0.553363,0.078521,-0.064664,0.507194,0.545883,0.597110,0.852289,0.046142
d_fires,3851135.0,0.845474,0.728177,0.000000,0.361248,0.680147,1.129292,7.873729,0.000000

In [6]:
show_summary(fall)

,count,mean,std,min,25%,50%,75%,max,nan (%)
elevation,3851135.0,52.236627,32.225412,-11.406961,24.754438,53.000000,77.078355,155.993200,0.000000
slope,3851135.0,2.096079,1.485652,0.000000,1.069072,1.768091,2.730465,22.356083,0.000000
aspect,3851135.0,176.065386,100.933582,0.000000,91.410355,175.375240,263.065060,359.999940,0.000000
d_roads,3851135.0,0.178238,0.184750,0.000000,0.042426,0.123693,0.256320,2.151023,0.000000
d_rivers,3851135.0,0.681790,0.511006,0.000000,0.268328,0.589407,0.999050,3.789512,0.000000
d_activity,3851135.0,0.036372,0.100837,0.000000,0.000000,0.000000,0.030000,1.623884,0.000000
tas,3812267.0,11.552069,0.295895,10.859999,11.329307,11.514056,11.747878,12.507919,1.009261
tasmax,3812267.0,15.341448,0.252267,14.623370,15.173379,15.374393,15.536273,15.995181,1.009261
tasmin,3812267.0,7.696105,0.445892,6.914687,7.365311,7.600045,7.915108,9.498369,1.009261
rainfall,3812267.0,52.661142,2.698392,42.628822,50.839718,52.419243,54.202763,65.213920,1.009261
sfcWind,3812267.0,3.871171,0.328444,2.676901,3.681285,3.863040,4.043578,5.520843,1.009261
hurs,3812267.0,84.414681,0.463975,82.536190,84.180020,84.522460,84.736070,85.181890,1.009261
ndvi,3849034.0,0.519235,0.096976,-0.192700,0.451575,0.513309,0.585699,0.771168,0.054555
d_fires,3851135.0,1.054450,0.759176,0.000000,0.483735,0.891964,1.443122,5.160088,0.000000